#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true
write_files:
  - path: /etc/ssh/sshd_config.d/01-harden-ssh.conf
    content: |
      PermitRootLogin no
      PasswordAuthentication no
      ChallengeResponseAuthentication no
  - path: /etc/sudoers.d/vault
    content: |
      vault ALL=(ALL) NOPASSWD:ALL
packages:
  - qemu-guest-agent
  - sudo
  - bash
ssh_pwauth: false # sshd service will be configured to accept password authentication method
chpasswd:
  expire: false # Don't ask for password reset after the first log-in
users:
  - default
  - name: vault
    lock_passwd: false
power_state:
  delay: now
  mode: reboot
  message: Rebooting after cloud-init completion
  condition: true
runcmd:
  - rc-update add qemu-guest-agent
