#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true
write_files:
  - path: /etc/ssh/sshd_config.d/01-harden-ssh.conf
    content: |
      PermitRootLogin no
      PasswordAuthentication no
      ChallengeResponseAuthentication no
  - path: /etc/sudoers.d/vault
    content: |
      vault ALL=(ALL) NOPASSWD:ALL
  - path: /etc/init.d/vault
    content: |
      #!/sbin/openrc-run

      name=$RC_SVCNAME
      cfgfile="/etc/vault.d/vault.hcl"
      command="/usr/local/bin/vault"
      command_args="server -config=/etc/vault.d/vault.hcl"
      command_user="vault"
      command_group="vault"
      command_background=true
      pidfile="/run/vault/vault.pid"

      depend() {
        need net
      }

      start_pre() {
        checkpath --directory --owner $command_user:$command_group --mode 0775 /run/$RC_SVCNAME
      }
    owner: 'root:root'
    permissions: '0755'
  - path: /root/install_vault.sh
    content: |
      #!/bin/bash
      product="vault"
      version="VAULT_VERSION"
      wget https://releases.hashicorp.com/${product}/${version}/${product}_${version}_linux_amd64.zip && \
        wget https://releases.hashicorp.com/${product}/${version}/${product}_${version}_SHA256SUMS && \
        wget https://releases.hashicorp.com/${product}/${version}/${product}_${version}_SHA256SUMS.sig && \
        wget -qO- https://www.hashicorp.com/.well-known/pgp-key.txt | gpg --import && \
        gpg --verify ${product}_${version}_SHA256SUMS.sig ${product}_${version}_SHA256SUMS && \
        grep ${product}_${version}_linux_amd64.zip ${product}_${version}_SHA256SUMS | sha256sum -c && \
        unzip ${product}_${version}_linux_amd64.zip -d /tmp && \
        mv /tmp/${product} /usr/local/bin/${product} && \
        rm -f ${product}_${version}_linux_amd64.zip ${product}_${version}_SHA256SUMS ${product}_${version}_SHA256SUMS.sig && \
        rm -f /tmp/LICENSE.txt

      user=vault
      group=vault
      vault_config=/etc/vault.d
      vault_config_file="$vault_config/vault.hcl"
      vault_data_folder="/var/lib/vault"
      service_file="/etc/init.d/vault"
      pidfile="/run/vault/vault.pid"    
      mkdir -p $vault_config
      mkdir -p $vault_data_folder
      chown $user:$group $vault_data_folder
      setcap cap_ipc_lock=+ep $(readlink -f $(which vault))
    owner: 'root:root'
    permissions: '0755'
packages:
  - qemu-guest-agent
  - sudo
  - bash
  - jq
  - openssl
  - curl
  - gpg
  - vim
  - gnupg 
  - libcap-setcap
ssh_pwauth: false # sshd service will be configured to accept password authentication method
password: RANDOMPASSWD # Set a password for alpine
chpasswd:
  expire: false # Don't ask for password reset after the first log-in
ssh_authorized_keys:
  - SSHKEY
users:
  - default
  - name: vault
    password: RANDOMPASSWD
    lock_passwd: false
    doas:
      - permit nopass vault as root
    ssh_authorized_keys:
      - SSHKEY
power_state:
  delay: now
  mode: reboot
  message: Rebooting after cloud-init completion
  condition: true
runcmd:
  - |
    rc-update add qemu-guest-agent
    rc-service qemu-guest-agent start
    bash /root/install_vault.sh